export enum Endpoint {
    SignIn = "/api/sign/in",
    SignOut = "/api/sign/out",
    GetLoggedUser = "/api/getLoggedUser",
    SignUp = "/api/sign/up",
    ProfileLoad = "/api/profile/load",
    ProfileEdit = "/api/profile/edit",
    ProfileChangePassword = "/api/profile/changePassword",
    UsersList = "/api/users/list",
    UsersSwitchEnabledState = "/api/users/switchEnabledState",
    UsersChangeRole = "/api/users/changeRole",
    CategoryList = "/api/category/list",
    CategoryAdd = "/api/category/add",
    CategoryRemove = "/api/category/remove",
    CategoryEdit = "/api/category/edit",
    ArticleAdd = "/api/article/add",
    ArticleEdit = "/api/article/edit",
    ArticleRemove = "/api/article/remove",
    ArticleList = "/api/article/list",
    GalleryList = "/api/gallery/list",
    GalleryAdd = "/api/gallery/add",
    GalleryRemove = "/api/gallery/remove",
    GalleryEdit = "/api/gallery/edit",
    GalleryItemList = "/api/gallery/itemList",
    GalleryItemAdd = "/api/gallery/itemAdd",
    GalleryItemRemove = "/api/gallery/itemRemove",
    GalleryItemEdit = "/api/gallery/itemEdit"
}
