-- MySQL Script generated by MySQL Workbench
-- Sun Oct 29 15:15:45 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema blog-test
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `blog-test` ;

-- -----------------------------------------------------
-- Schema blog-test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog-test` DEFAULT CHARACTER SET utf8 ;
USE `blog-test` ;

-- -----------------------------------------------------
-- Table `blog-test`.`UserRole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog-test`.`UserRole` ;

CREATE TABLE IF NOT EXISTS `blog-test`.`UserRole` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(55) NOT NULL,
  `Description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog-test`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog-test`.`User` ;

CREATE TABLE IF NOT EXISTS `blog-test`.`User` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(55) NULL,
  `Surname` VARCHAR(55) NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `Nickname` VARCHAR(55) NOT NULL,
  `LastSignInDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Role` INT UNSIGNED NULL,
  `Enabled` BIT(1) NOT NULL DEFAULT 1,
  `Avatar` VARCHAR(255) NULL DEFAULT 'avatar.png',
  `RestorePasswordKey` VARCHAR(255) NULL,
  `ActivationEmailKey` VARCHAR(255) NULL,
  `Activated` BIT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Nickname_UNIQUE` (`Nickname` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC),
  INDEX `fk_User(Role)_UserRole(Id)_idx` (`Role` ASC),
  CONSTRAINT `fk_User(Role)_UserRole(Id)`
  FOREIGN KEY (`Role`)
  REFERENCES `blog-test`.`UserRole` (`Id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog-test`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog-test`.`Category` ;

CREATE TABLE IF NOT EXISTS `blog-test`.`Category` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(55) NOT NULL,
  `Description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog-test`.`Gallery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog-test`.`Gallery` ;

CREATE TABLE IF NOT EXISTS `blog-test`.`Gallery` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(55) NOT NULL,
  `Description` VARCHAR(255) NOT NULL,
  `Author` INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`Id`),
  INDEX `fk_Gallery(Autor)_User(id)_idx` (`Author` ASC),
  CONSTRAINT `fk_Gallery(Autor)_User(id)`
  FOREIGN KEY (`Author`)
  REFERENCES `blog-test`.`User` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog-test`.`GalleryItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog-test`.`GalleryItem` ;

CREATE TABLE IF NOT EXISTS `blog-test`.`GalleryItem` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ImageName` VARCHAR(55) NOT NULL,
  `Title` VARCHAR(255) NULL,
  `Gallery` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_GalleryItem(Gallery)_Gallery(Id)_idx` (`Gallery` ASC),
  CONSTRAINT `fk_GalleryItem(Gallery)_Gallery(Id)`
  FOREIGN KEY (`Gallery`)
  REFERENCES `blog-test`.`Gallery` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog-test`.`Article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog-test`.`Article` ;

CREATE TABLE IF NOT EXISTS `blog-test`.`Article` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(55) NOT NULL,
  `PreviewImage` VARCHAR(55) NOT NULL,
  `Content` LONGTEXT NOT NULL,
  `Author` INT UNSIGNED NOT NULL DEFAULT 1,
  `PublishDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EditDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Category` INT UNSIGNED NOT NULL,
  `Visible` BIT(1) NOT NULL DEFAULT 1,
  `Gallery` INT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Article(Author)_User(Id)_idx` (`Author` ASC),
  INDEX `fk_Article(Category)_Category(Id)_idx` (`Category` ASC),
  INDEX `fk_Article(Gallery)_Gallery(Id)_idx` (`Gallery` ASC),
  CONSTRAINT `fk_Article(Author)_User(Id)`
  FOREIGN KEY (`Author`)
  REFERENCES `blog-test`.`User` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Article(Category)_Category(Id)`
  FOREIGN KEY (`Category`)
  REFERENCES `blog-test`.`Category` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Article(Gallery)_Gallery(Id)`
  FOREIGN KEY (`Gallery`)
  REFERENCES `blog-test`.`Gallery` (`Id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog-test`.`ArticleRating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog-test`.`ArticleRating` ;

CREATE TABLE IF NOT EXISTS `blog-test`.`ArticleRating` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Article` INT UNSIGNED NOT NULL,
  `User` INT UNSIGNED NOT NULL,
  `Rating` FLOAT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_ArticleRating(User)_User(Id)_idx` (`User` ASC),
  INDEX `fk_ArticleRating(Article)_Article(Id)_idx` (`Article` ASC),
  CONSTRAINT `fk_ArticleRating(User)_User(Id)`
  FOREIGN KEY (`User`)
  REFERENCES `blog-test`.`User` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ArticleRating(Article)_Article(Id)`
  FOREIGN KEY (`Article`)
  REFERENCES `blog-test`.`Article` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog-test`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog-test`.`Comment` ;

CREATE TABLE IF NOT EXISTS `blog-test`.`Comment` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Article` INT UNSIGNED NOT NULL,
  `ParentComment` INT UNSIGNED NULL DEFAULT NULL,
  `Author` INT UNSIGNED NOT NULL DEFAULT 1,
  `PublishDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Content` TEXT NOT NULL,
  `Visible` BIT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`Id`),
  INDEX `fk_Comment(Article)_Article(Id)_idx` (`Article` ASC),
  INDEX `fk_Comment(Author)_User(Id)_idx` (`Author` ASC),
  INDEX `fk_Comment(ParentComment)_Comment(id)_idx` (`ParentComment` ASC),
  CONSTRAINT `fk_Comment(Article)_Article(Id)`
  FOREIGN KEY (`Article`)
  REFERENCES `blog-test`.`Article` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment(Author)_User(Id)`
  FOREIGN KEY (`Author`)
  REFERENCES `blog-test`.`User` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment(ParentComment)_Comment(id)`
  FOREIGN KEY (`ParentComment`)
  REFERENCES `blog-test`.`Comment` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog-test`.`UserQuestion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog-test`.`UserQuestion` ;

CREATE TABLE IF NOT EXISTS `blog-test`.`UserQuestion` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `User` INT UNSIGNED NOT NULL,
  `Question` VARCHAR(255) NOT NULL,
  `Answer` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_UserQuestion(User)_User(Id)_idx` (`User` ASC),
  CONSTRAINT `fk_UserQuestion(User)_User(Id)`
  FOREIGN KEY (`User`)
  REFERENCES `blog-test`.`User` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;

SET SQL_MODE = '';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `blog-test`.`UserRole`
-- -----------------------------------------------------
START TRANSACTION;
USE `blog-test`;
INSERT INTO `blog-test`.`UserRole` (`Id`, `Name`, `Description`) VALUES (1, 'User', 'Basic user, can write comments and rate articles.');
INSERT INTO `blog-test`.`UserRole` (`Id`, `Name`, `Description`) VALUES (2, 'Editor', 'User which can write articles and edit owned articles.');
INSERT INTO `blog-test`.`UserRole` (`Id`, `Name`, `Description`) VALUES (3, 'Moderator', 'User which can edit all articles and delete all comments.');
INSERT INTO `blog-test`.`UserRole` (`Id`, `Name`, `Description`) VALUES (4, 'Administrator', 'User which has unlimited access to administration of blog-test.');

COMMIT;


-- -----------------------------------------------------
-- Data for table `blog-test`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `blog-test`;
INSERT INTO `blog-test`.`User` (`Id`, `Name`, `Surname`, `Email`, `Password`, `Nickname`, `LastSignInDate`, `Role`, `Enabled`, `Avatar`, `RestorePasswordKey`, `ActivationEmailKey`, `Activated`) VALUES (1, NULL, NULL, 'unknown@example.com', 'password', 'unknown', '1970-01-01 00:00:00', 1, 0, NULL, NULL, NULL, 0);
INSERT INTO `blog-test`.`User` (`Id`, `Name`, `Surname`, `Email`, `Password`, `Nickname`, `LastSignInDate`, `Role`, `Enabled`, `Avatar`, `RestorePasswordKey`, `ActivationEmailKey`, `Activated`) VALUES (DEFAULT, NULL, NULL, 'administrator@example.com', '$2b$12$geUoIgWeXDbaEicv3G3rPeo2jBu3YqGsyp7/z/p00EIQsyQsq29LG', 'administrator', '1970-01-01 00:00:00', 4, 1, NULL, NULL, NULL, 1);

COMMIT;

